# Generated by Django 2.2.2 on 2019-11-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='site_key',
            field=models.CharField(blank=True, default='b7265a9e874f4068b0b48d45ef97595a', max_length=32, unique=True),
        ),
    ]
