# Generated by Django 2.2.2 on 2019-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='site_key',
            field=models.CharField(blank=True, default='03fbadcdc82d4cc9a77851355587735a', max_length=32, unique=True),
        ),
    ]
