# Generated by Django 2.2.2 on 2019-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191113_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='discord_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='site_key',
            field=models.CharField(blank=True, default='a1f426383ff54037b56f31c2f0cf18c6', max_length=32, unique=True),
        ),
    ]
