# Generated by Django 2.2.2 on 2019-11-11 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ethical Hacking Meeting - Weekly Meetup', max_length=100)),
                ('location', models.CharField(default='G01 at CSSE', max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('info', models.TextField(default='Bring your laptops')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
