# Generated by Django 2.2.2 on 2019-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ethical Hacking Meeting - Weekly Meetup', max_length=100)),
                ('location', models.CharField(default='G01 at CSSE', max_length=100)),
                ('time', models.DateTimeField()),
                ('info', models.TextField(default='Bring your laptops!')),
            ],
        ),
    ]
